In [1]:
import numpy as np

def softmax(x):
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum()
x = np.array([1.0, 2.0, 3.0])
print(softmax(x))

[0.09003057 0.24472847 0.66524096]


In [ ]:
import numpy as np
def safe_softmax(x):
    max_x = np.max(x, axis = -1, keepdims=True)
    exp_x = np.exp(x - max_x)
    sum_exp_x = np.sum(exp_x, axis=-1, keepdims=True)

    return exp_x / sum_exp_x
# 一维输入测试
x = np.array([1, 2, 3])
print(softmax(x), '\n')  # 输出 ≈ [0.0900, 0.2447, 0.6652]

# 二维输入测试
x = np.array([[1, 2, 3],
              [2, 4, 6]])
print(softmax(x))  

[0.09003057 0.24472847 0.66524096] 

[[0.00548473 0.01490905 0.04052699]
 [0.01490905 0.11016379 0.8140064 ]]


In [ ]:
def attention(Q, K, V):
    # Q, K, V 的维度 shape 为 (batch_size, seq_len, d_model)
    # 计算 Q 和 K 的转置
    attention_score = np.matmul(Q, K.transpose(0, 2, 1)) / np.sqrt(Q.shape[-1])

    attention_score = safe_softmax(attention_score)
    # 计算加权和
    attention_output = np.matmul(attention_score, V)
    return attention_output
Q = np.array([[[1, 2, 3], [4, 5, 6]]])
K = np.array([[[1, 0, 0], [0, 1, 0]]])
V = np.array([[[0, 1, 0], [1, 0, 1]]])
print(attention(Q, K, V))  # 输出 [[[2.5, 2.0, 3.5]]]

ValueError: axes don't match array